/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiWorkspaceAssetRouteImport } from './routes/api/workspace-asset'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiContentVersionRouteImport } from './routes/api/content-version'
import { Route as LangSplatRouteImport } from './routes/$lang/$'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ApiWorkspaceAssetRoute = ApiWorkspaceAssetRouteImport.update({
  id: '/api/workspace-asset',
  path: '/api/workspace-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentVersionRoute = ApiContentVersionRouteImport.update({
  id: '/api/content-version',
  path: '/api/content-version',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/$': typeof LangSplatRoute
  '/api/content-version': typeof ApiContentVersionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/workspace-asset': typeof ApiWorkspaceAssetRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/$': typeof LangSplatRoute
  '/api/content-version': typeof ApiContentVersionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/workspace-asset': typeof ApiWorkspaceAssetRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/$': typeof LangSplatRoute
  '/api/content-version': typeof ApiContentVersionRoute
  '/api/search': typeof ApiSearchRoute
  '/api/workspace-asset': typeof ApiWorkspaceAssetRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/$'
    | '/api/content-version'
    | '/api/search'
    | '/api/workspace-asset'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/$'
    | '/api/content-version'
    | '/api/search'
    | '/api/workspace-asset'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/$'
    | '/api/content-version'
    | '/api/search'
    | '/api/workspace-asset'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiContentVersionRoute: typeof ApiContentVersionRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiWorkspaceAssetRoute: typeof ApiWorkspaceAssetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/workspace-asset': {
      id: '/api/workspace-asset'
      path: '/api/workspace-asset'
      fullPath: '/api/workspace-asset'
      preLoaderRoute: typeof ApiWorkspaceAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-version': {
      id: '/api/content-version'
      path: '/api/content-version'
      fullPath: '/api/content-version'
      preLoaderRoute: typeof ApiContentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangSplatRoute: typeof LangSplatRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangSplatRoute: LangSplatRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiContentVersionRoute: ApiContentVersionRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiWorkspaceAssetRoute: ApiWorkspaceAssetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
